//Type for fetch orders
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
//Type for fetch orders
export const FETCH_ORDERS_BY_ID_REQUEST = 'FETCH_ORDERS_BY_ID_REQUEST';
export const FETCH_ORDERS_BY_ID_SUCCESS = 'FETCH_ORDERS_BY_ID_SUCCESS';
export const FETCH_ORDERS_BY_ID_FAIL = 'FETCH_ORDERS_BY_ID_FAIL';
//Type for fetch packages
export const FETCH_PACKAGES_REQUEST = 'FETCH_PACKAGES_REQUEST';
export const FETCH_PACKAGES_SUCCESS = 'FETCH_PACKAGES_SUCCESS';
export const FETCH_PACKAGES_FAIL = 'FETCH_PACKAGES_FAIL';
//Type for adding clients
export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';
//Type for updating client status
export const UPDATE_CLIENT_STATUS_REQUEST = 'UPDATE_CLIENT_STATUS_REQUEST';
export const UPDATE_CLIENT_STATUS_SUCCESS = 'UPDATE_CLIENT_STATUS_SUCCESS';
export const UPDATE_CLIENT_STATUS_FAIL = 'UPDATE_CLIENT_STATUS_FAIL';
//Type for adding packages
export const ADD_PACKAGE_REQUEST = 'ADD_PACKAGE_REQUEST';
export const ADD_PACKAGE_SUCCESS = 'ADD_PACKAGE_SUCCESS';
export const ADD_PACKAGE_FAIL = 'ADD_PACKAGE_FAIL';
